apiVersion: v1
kind: Service
metadata:
  name: {{ include "backstage.fullname" . }}
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
    # Private load balancer for AKS. AKS needs network contributor on the vnet.
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 7007
      protocol: TCP
  selector:
    {{- include "backstage.selectorLabels" . | nindent 4 }}
